/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SemPermissaoRouteImport } from './routes/sem-permissao'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConsultoresSlugRouteImport } from './routes/consultores.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated/admin.areas'
import { Route as AuthenticatedAdminMetricasRouteImport } from './routes/_authenticated/admin.metricas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedConteudosIndexRouteImport } from './routes/_authenticated/conteudos.index'
import { Route as AuthenticatedConteudosSlugRouteImport } from './routes/_authenticated/conteudos.$slug'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelLeadsRouteImport } from './routes/_authenticated/painel.leads'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated/painel.perfil'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as AuthenticatedAdminConsultoresIndexRouteImport } from './routes/_authenticated/admin.consultores.index'
import { Route as AuthenticatedAdminConsultoresIdRouteImport } from './routes/_authenticated/admin.consultores.$id'
import { Route as AuthenticatedPainelConteudosIndexRouteImport } from './routes/_authenticated/painel.conteudos.index'
import { Route as AuthenticatedPainelConteudosIdRouteImport } from './routes/_authenticated/painel.conteudos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SemPermissaoRoute = SemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoresSlugRoute = ConsultoresSlugRouteImport.update({
  id: '/consultores/$slug',
  path: '/consultores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/admin/areas',
  path: '/admin/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMetricasRoute =
  AuthenticatedAdminMetricasRouteImport.update({
    id: '/admin/metricas',
    path: '/admin/metricas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConteudosIndexRoute =
  AuthenticatedConteudosIndexRouteImport.update({
    id: '/conteudos/',
    path: '/conteudos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConteudosSlugRoute =
  AuthenticatedConteudosSlugRouteImport.update({
    id: '/conteudos/$slug',
    path: '/conteudos/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelLeadsRoute =
  AuthenticatedPainelLeadsRouteImport.update({
    id: '/painel/leads',
    path: '/painel/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/painel/perfil',
    path: '/painel/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminConsultoresIndexRoute =
  AuthenticatedAdminConsultoresIndexRouteImport.update({
    id: '/admin/consultores/',
    path: '/admin/consultores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConsultoresIdRoute =
  AuthenticatedAdminConsultoresIdRouteImport.update({
    id: '/admin/consultores/$id',
    path: '/admin/consultores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelConteudosIndexRoute =
  AuthenticatedPainelConteudosIndexRouteImport.update({
    id: '/painel/conteudos/',
    path: '/painel/conteudos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelConteudosIdRoute =
  AuthenticatedPainelConteudosIdRouteImport.update({
    id: '/painel/conteudos/$id',
    path: '/painel/conteudos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/consultores/$slug': typeof ConsultoresSlugRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/metricas': typeof AuthenticatedAdminMetricasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/conteudos/$slug': typeof AuthenticatedConteudosSlugRoute
  '/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/conteudos/': typeof AuthenticatedConteudosIndexRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/admin/consultores/$id': typeof AuthenticatedAdminConsultoresIdRoute
  '/painel/conteudos/$id': typeof AuthenticatedPainelConteudosIdRoute
  '/admin/consultores/': typeof AuthenticatedAdminConsultoresIndexRoute
  '/painel/conteudos/': typeof AuthenticatedPainelConteudosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/consultores/$slug': typeof ConsultoresSlugRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/metricas': typeof AuthenticatedAdminMetricasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/conteudos/$slug': typeof AuthenticatedConteudosSlugRoute
  '/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/conteudos': typeof AuthenticatedConteudosIndexRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/admin/consultores/$id': typeof AuthenticatedAdminConsultoresIdRoute
  '/painel/conteudos/$id': typeof AuthenticatedPainelConteudosIdRoute
  '/admin/consultores': typeof AuthenticatedAdminConsultoresIndexRoute
  '/painel/conteudos': typeof AuthenticatedPainelConteudosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/consultores/$slug': typeof ConsultoresSlugRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/admin/metricas': typeof AuthenticatedAdminMetricasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/conteudos/$slug': typeof AuthenticatedConteudosSlugRoute
  '/_authenticated/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/conteudos/': typeof AuthenticatedConteudosIndexRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/admin/consultores/$id': typeof AuthenticatedAdminConsultoresIdRoute
  '/_authenticated/painel/conteudos/$id': typeof AuthenticatedPainelConteudosIdRoute
  '/_authenticated/admin/consultores/': typeof AuthenticatedAdminConsultoresIndexRoute
  '/_authenticated/painel/conteudos/': typeof AuthenticatedPainelConteudosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/sem-permissao'
    | '/sitemap.xml'
    | '/consultores/$slug'
    | '/admin/areas'
    | '/admin/metricas'
    | '/admin/usuarios'
    | '/conteudos/$slug'
    | '/painel/leads'
    | '/painel/perfil'
    | '/api/media/$'
    | '/admin/'
    | '/conteudos/'
    | '/painel/'
    | '/admin/consultores/$id'
    | '/painel/conteudos/$id'
    | '/admin/consultores/'
    | '/painel/conteudos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/sem-permissao'
    | '/sitemap.xml'
    | '/consultores/$slug'
    | '/admin/areas'
    | '/admin/metricas'
    | '/admin/usuarios'
    | '/conteudos/$slug'
    | '/painel/leads'
    | '/painel/perfil'
    | '/api/media/$'
    | '/admin'
    | '/conteudos'
    | '/painel'
    | '/admin/consultores/$id'
    | '/painel/conteudos/$id'
    | '/admin/consultores'
    | '/painel/conteudos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/sem-permissao'
    | '/sitemap.xml'
    | '/consultores/$slug'
    | '/_authenticated/admin/areas'
    | '/_authenticated/admin/metricas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/conteudos/$slug'
    | '/_authenticated/painel/leads'
    | '/_authenticated/painel/perfil'
    | '/api/media/$'
    | '/_authenticated/admin/'
    | '/_authenticated/conteudos/'
    | '/_authenticated/painel/'
    | '/_authenticated/admin/consultores/$id'
    | '/_authenticated/painel/conteudos/$id'
    | '/_authenticated/admin/consultores/'
    | '/_authenticated/painel/conteudos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SemPermissaoRoute: typeof SemPermissaoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ConsultoresSlugRoute: typeof ConsultoresSlugRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-permissao': {
      id: '/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof SemPermissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultores/$slug': {
      id: '/consultores/$slug'
      path: '/consultores/$slug'
      fullPath: '/consultores/$slug'
      preLoaderRoute: typeof ConsultoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/admin/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/metricas': {
      id: '/_authenticated/admin/metricas'
      path: '/admin/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AuthenticatedAdminMetricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudos/': {
      id: '/_authenticated/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof AuthenticatedConteudosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudos/$slug': {
      id: '/_authenticated/conteudos/$slug'
      path: '/conteudos/$slug'
      fullPath: '/conteudos/$slug'
      preLoaderRoute: typeof AuthenticatedConteudosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/leads': {
      id: '/_authenticated/painel/leads'
      path: '/painel/leads'
      fullPath: '/painel/leads'
      preLoaderRoute: typeof AuthenticatedPainelLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/painel/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/consultores/': {
      id: '/_authenticated/admin/consultores/'
      path: '/admin/consultores'
      fullPath: '/admin/consultores/'
      preLoaderRoute: typeof AuthenticatedAdminConsultoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/consultores/$id': {
      id: '/_authenticated/admin/consultores/$id'
      path: '/admin/consultores/$id'
      fullPath: '/admin/consultores/$id'
      preLoaderRoute: typeof AuthenticatedAdminConsultoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/conteudos/': {
      id: '/_authenticated/painel/conteudos/'
      path: '/painel/conteudos'
      fullPath: '/painel/conteudos/'
      preLoaderRoute: typeof AuthenticatedPainelConteudosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/conteudos/$id': {
      id: '/_authenticated/painel/conteudos/$id'
      path: '/painel/conteudos/$id'
      fullPath: '/painel/conteudos/$id'
      preLoaderRoute: typeof AuthenticatedPainelConteudosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedAdminMetricasRoute: typeof AuthenticatedAdminMetricasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedConteudosSlugRoute: typeof AuthenticatedConteudosSlugRoute
  AuthenticatedPainelLeadsRoute: typeof AuthenticatedPainelLeadsRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedConteudosIndexRoute: typeof AuthenticatedConteudosIndexRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedAdminConsultoresIdRoute: typeof AuthenticatedAdminConsultoresIdRoute
  AuthenticatedPainelConteudosIdRoute: typeof AuthenticatedPainelConteudosIdRoute
  AuthenticatedAdminConsultoresIndexRoute: typeof AuthenticatedAdminConsultoresIndexRoute
  AuthenticatedPainelConteudosIndexRoute: typeof AuthenticatedPainelConteudosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
  AuthenticatedAdminMetricasRoute: AuthenticatedAdminMetricasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedConteudosSlugRoute: AuthenticatedConteudosSlugRoute,
  AuthenticatedPainelLeadsRoute: AuthenticatedPainelLeadsRoute,
  AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedConteudosIndexRoute: AuthenticatedConteudosIndexRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedAdminConsultoresIdRoute: AuthenticatedAdminConsultoresIdRoute,
  AuthenticatedPainelConteudosIdRoute: AuthenticatedPainelConteudosIdRoute,
  AuthenticatedAdminConsultoresIndexRoute:
    AuthenticatedAdminConsultoresIndexRoute,
  AuthenticatedPainelConteudosIndexRoute:
    AuthenticatedPainelConteudosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SemPermissaoRoute: SemPermissaoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ConsultoresSlugRoute: ConsultoresSlugRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
